### ISSUE TITLE
'score' layer contains only 2 classes (0 and 1)

### ISSUE THREAD

**Issue by aram200** [briannemsick/fcn_satellite#3]
Hi, thank you for sharing your codes.
I am getting a lot of help from your answer.

I followed exactly the procedure that you describe.
I have tried to train for 10000 iterations with three classes, however, the last score layer contained only 2 classes (0 and 1). I did not modify net.py (output number is set 3).  

How many iterates to get a 'deploy.caffemodel' which you uploaded ? (https://www.dropbox.com/s/i2e2eceus42vvra/deploy.caffemodel?dl=0)
I want to know the reason for the problem. Is this caused by insufficient iteration numbers?

please give me any idea!
thanks

**Comment by briannemsick** [comment]
Hi,

Based on the past several issues you've raised, I have the following pieces of advice.

1. Complete the Caffe tutorials

2. Read the reference FCN repository: https://github.com/shelhamer/fcn.berkeleyvision.org

This repository is an adaptation of the FCN repository for a very specific dataset.

The weights I have linked on dropbox, are FCN VGG16 weights as described in the README.

**Comment by aram200** [comment]
thank you for your advice!!
